### ISSUE TITLE
Issue on Jamal machine: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

### ISSUE THREAD

**Issue by andiads** [andiads/scm-covid-id#20]
There is an unknown issue that came from @jamalludin13 local machine.

these are the error logs from the console

>  :: Spring Boot ::        (v2.2.7.RELEASE)
> 
> 2020-05-16 12:43:07.445  INFO 8944 --- [  restartedMain] c.n.app.ScmCovid19IndonesiaApplication   : Starting ScmCovid19IndonesiaApplication on JAMALUDIN with PID 8944 (D:\hello\scm-covid-id-development\target\classes started by Jamalludin in D:\hello\scm-covid-id-development)
> 2020-05-16 12:43:07.449  INFO 8944 --- [  restartedMain] c.n.app.ScmCovid19IndonesiaApplication   : No active profile set, falling back to default profiles: default
> 2020-05-16 12:43:07.445  INFO 8944 --- [  restartedMain] c.n.app.ScmCovid19IndonesiaApplication   : Starting ScmCovid19IndonesiaApplication on JAMALUDIN with PID 8944 (D:\hello\scm-covid-id-development\target\classes started by Jamalludin in D:\hello\scm-covid-id-development)
> 2020-05-16 12:43:07.449  INFO 8944 --- [  restartedMain] c.n.app.ScmCovid19IndonesiaApplication   : No active profile set, falling back to default profiles: default
> 2020-05-16 12:43:13.958  INFO 8944 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
> 2020-05-16 12:43:13.962  INFO 8944 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
> 2020-05-16 12:43:13.958  INFO 8944 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
> 2020-05-16 12:43:13.962  INFO 8944 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
> 2020-05-16 12:43:51.282  INFO 8944 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
> 2020-05-16 12:43:51.282  INFO 8944 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
> 2020-05-16 12:43:52.380  INFO 8944 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 869ms. Found 12 JPA repository interfaces.
> 2020-05-16 12:43:52.380  INFO 8944 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 869ms. Found 12 JPA repository interfaces.
> 2020-05-16 12:44:03.466  INFO 8944 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
> 2020-05-16 12:44:03.466  INFO 8944 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
> 2020-05-16 12:44:03.732  INFO 8944 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2020-05-16 12:44:03.732  INFO 8944 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2020-05-16 12:44:03.732  INFO 8944 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.34]
> 2020-05-16 12:44:03.732  INFO 8944 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.34]
> 2020-05-16 12:44:05.241  INFO 8944 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2020-05-16 12:44:05.241  INFO 8944 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2020-05-16 12:44:05.242  INFO 8944 --- [  restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 51280 ms
> 2020-05-16 12:44:05.242  INFO 8944 --- [  restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 51280 ms
> 2020-05-16 12:44:07.766  WARN 8944 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsatisfied dependency expressed through method 'flywayInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
> 2020-05-16 12:44:07.766  WARN 8944 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsatisfied dependency expressed through method 'flywayInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
> 2020-05-16 12:44:07.867  INFO 8944 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
> 2020-05-16 12:44:07.867  INFO 8944 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
> 2020-05-16 12:44:08.896  INFO 8944 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2020-05-16 12:44:08.896  INFO 8944 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2020-05-16 12:44:09.197 ERROR 8944 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
> 
> Reason: Failed to determine a suitable driver class
> 
> 
> Action:
> 
> Consider the following:
> 	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
> 	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
> 
> 2020-05-16 12:44:09.197 ERROR 8944 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
> 
> Reason: Failed to determine a suitable driver class
> 
> 
> Action:
> 
> Consider the following:
> 	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
> 	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
> 

I thought this error is caused by **Maven** build dependency and repository that still cached from previous build. And catch the error while importing new / latest development source code.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[issue.txt](https://github.com/andiads/scm-covid-id/files/4637961/issue.txt)

**Comment by jamalludin13** [comment]
Issue fixed.
Caused by: Local maven repository cache
Fix methods: 
1. Clear/delete maven local repository cache at %USERS%/,m2/repository
2. Clean install and build from CLI: **mvnw clean install** and **mvnw spring-boot:run**
3. Update MariaDB (or XAMPP) version to latest version. Since current Jamal local mariaDB machine version is 10.2 and it has incompatibility with flyway that requiring 10.4 or above latest version to make it work.
